---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Indicolite.
--- DateTime: 2026/8/24 15:08
---
-- 第二阶段：Redis预占订单
-- 这里只写入预占记录和待发送ZSet，不再写入Redis Stream

-- 参数
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]
local messageId = ARGV[4]
local createdAt = ARGV[5]

-- Redis Key
local stockKey = 'seckill:stock:' .. voucherId
local orderMapKey = 'seckill:order-map:' .. voucherId
local reservationKey = 'seckill:reservation:' .. orderId
local pendingKey = 'seckill:publish:pending'

-- 1. 检查库存
local stock = tonumber(redis.call('get', stockKey))
if stock == nil or stock <= 0 then
    return 1
end

-- 2. 检查该用户是否已经抢过该优惠券
if redis.call('hexists', orderMapKey, userId) == 1 then
    return 2
end

-- 3. 扣减Redis库存
redis.call('incrby', stockKey, -1)

-- 4. 记录用户对应的订单ID
redis.call('hset', orderMapKey, userId, orderId)

-- 5. 保存订单预占记录
redis.call(
        'hset',
        reservationKey,
        'orderId', orderId,
        'messageId', messageId,
        'userId', userId,
        'voucherId', voucherId,
        'status', 'PREPARED',
        'publishAttempts', '0',
        'nextRetryAt', createdAt,
        'createdAt', createdAt
)

-- 6. 加入待发送ZSet
-- score使用时间戳，后台可以查找“到时间需要发送”的订单
redis.call('zadd', pendingKey, createdAt, orderId)

-- 0成功，1库存不足，2重复下单
return 0