---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Indicolite.
--- DateTime: 2026/8/17 23:20
---


-- 获取锁中的线程标识
local id = redis.call("get", KEYS[1])
-- 比较Id是否等于当前线程标识
if(id==ARGV[1])then
    -- 释放锁
    return redis.call("del", KEYS[1])
end
return 0
